---
name: UDFMailchimp
---

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.michaeljjames_udf_cache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "michaeljjames_udf_cache"